name: flake8 Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - uses: py-actions/flake8@v1
      - name: flake8 Lint
        with:
          ignore: "E402","F841","F401","E302","E305"
          max-line-length: "200"
